name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: mkdir coverage
      - run: npm test:coverage
#      - name: upload test coverage badge
# uses: actions/upload-artifact@v1
# with:
#  name: coverage-badge
#  path: output/coverage/badge.svg
    env:
      CI: true
